name: karya_hizib
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_bloc: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:   
    - hamzanwadi.jpeg
    - keluarga.jpg
    - pendidikan.jpg
    - pendiri.jpg
    - datok.jpg    
    - fariza.jpg    
    - salam.jpg
    - zam.png

    #gambar hizib
    - hizib1.png
    - hizib2.png
    - hizib3.png
    - hizib4.png
    - hizib5.png
    - hizib6.png
    - hizib7.png
    - hizib8.png
    - hizib9.png
    - hizib10.png
    - hizib11.png
    - hizib12.png
    - hizib13.png
    - hizib14.png
    - hizib15.png
    - hizib16.png
    - hizib17.png
    - hizib18.png
    - hizib19.png
    - hizib20.png
    - hizib21.png
    - hizib22.png
    - hizib23.png
    - hizib24.png
    - hizib25.png
    - hizib26.png
    - hizib27.png
    - hizib28.png
    - hizib29.png
    - hizib30.png
    - hizib31.png
    - hizib32.png
    - hizib33.png
    - hizib34.png
    - hizib35.png
    - hizib36.png
    - hizib37.png
    - hizib38.png
    - hizib39.png
    - hizib40.png
    - hizib41.png
    - hizib42.png
    - hizib43.png
    - hizib44.png
    - hizib45.png
    - hizib46.png
    - hizib47.png
    - hizib48.png
    - hizib49.png

    #gambar barzanji
    - barzanji1.png
    - barzanji2.png
    - barzanji3.png
    - barzanji4.png
    - barzanji5.png
    - barzanji6.png
    - barzanji7.png
    - barzanji8.png
    - barzanji9.png
    - barzanji10.png
    - barzanji11.png
    - barzanji12.png
    - barzanji13.png
    - barzanji14.png
    - barzanji15.png
    - barzanji16.png
    - barzanji17.png
    - barzanji18.png
    - barzanji19.png
    - barzanji20.png
    - barzanji21.png
    - barzanji22.png
    - barzanji23.png
    - barzanji24.png
    - barzanji25.png
    - barzanji26.png
    - barzanji27.png
    - barzanji28.png
    - barzanji29.png
    - barzanji30.png
    - barzanji31.png
    - barzanji32.png
    - barzanji33.png
    - barzanji34.png
    - barzanji35.png
    - barzanji36.png

    #gambar biografi
    - biografi1.png
    - biografi2.png
    - biografi3.png
    - biografi4.png
    - biografi5.png
    - biografi6.png
    - biografi7.png
    - biografi8.png
    - biografi9.png
    - biografi10.png
    - biografi11.png
    - biografi12.png
    - biografi13.png
    - biografi14.png
    - biografi15.png
    - biografi16.png
    - biografi17.png
    - biografi18.png
    - biografi19.png
    - biografi20.png
    - biografi21.png
    - biografi22.png
    - biografi23.png
    - biografi24.png
    

    #gambar nahdlatulz-zainiyah
    - zainiyah1.png
    - zainiyah2.png
    - zainiyah3.png
    - zainiyah4.png
    - zainiyah5.png
    - zainiyah6.png
    - zainiyah7.png
    - zainiyah8.png
    - zainiyah9.png
    - zainiyah10.png
    - zainiyah11.png

    #gambar batu ngompal
    - batu0.png
    - batu1.png
    - batu2.png
    - batu3.png
    - batu4.png
    - batu5.png
    - batu6.png
    - batu7.png
    - batu8.png
    - batu9.png


    #tentang apliaksi
    - fariza1.jpg
    - fariza2.jpg
    - fariza3.jpg
    - fariza4.jpg


    



    

   
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
